---
title: "simple forecasting methods"
author: "Millie Chapman"
date: "2/16/2021"
output: github_document
---

```{r message=FALSE}
library(tidyverse)
library(ISOweek) 
library(forecast)
library(fable)
library(tsibble)
library(tsibbledata)
library(lubridate)
library(dplyr)
```

Explore other simple forecasting methods

```{r message=FALSE}
## Get the latest beetle target data.  
download.file("https://data.ecoforecast.org/targets/beetles/beetles-targets.csv.gz",
              "beetles-targets.csv.gz")
targets <-  read_csv("beetles-targets.csv.gz")
```

Make tsibble! (richness data)
```{r}
targets_ts <- targets %>%
  select(siteID, time, richness) %>%
  mutate(iso_week = ISOweek::date2ISOweek(time)) %>%
  separate(iso_week, into = c("year", "week", "day")) 
  mutate(time = as.Date(time)) #%>%
 # mutate(time = yearmonth(time)) %>% #month year to start...
 # group_by(time, siteID) %>%
 # summarise(richness = mean(richness, na.rm = TRUE))
  #separate(iso_week, into = c("year", "week", "day")) %>%
  # filter(siteID %in% c("DSNY", "OSBS"))

targets_tsb <- as_tsibble(targets_ts, key = siteID, index = time)
```

```{r}
targets_tsb <- targets_tsb %>%
  group_by_key() %>%
  #fill_gaps() %>%
  #tidyr::fill(richness, .direction = "down") %>%
  filter(year(time) < 2020)
```

Mean forecast:

$$\hat{Y}_{T+h|T} = \bar{Y}$$

```{r}
targets_tsb %>% model(MEAN(targets_tsb))
```

Naïve method

$$\hat{Y}_{T+h|T} = Y_T$$

```{r}
targets_tsb %>% model(NAIVE(targets_tsb))
```

Seasonal naïve method

$$\hat{Y}_{T+h|T} = Y_{T+h-m(k+1)}$$

```{r}
targets_tsb %>% model(SNAIVE(targets_tsb ~ lag("year")))
```

Drift method: 

```{r}
targets_tsb %>% model(RW(targets_tsb ~ drift()))
```

Filling in NAs
```{r}
train <- targets_tsb %>%
  group_by_key() %>%
  fill_gaps() %>%
  tidyr::fill(richness, .direction = "down") %>%
  filter(year(time) < 2020)
```

Trying a handful of models 
```{r}
fit <- train %>%
  model(
    ets = ETS(richness),
    arima = ARIMA(richness),
    snaive = SNAIVE(richness)
  ) %>%
  mutate(mixed = (ets + arima + snaive) / 3)
```

Forecast!
```{r}
fc <- fit %>%
  forecast(h = "12 months") 
```

```{r}
fc %>%
  filter(siteID == "ABBY") %>%
  autoplot(train, level = NULL)
fc %>%
  filter(siteID == "BART") %>%
  autoplot(train, level = NULL)

```  


```{r}
fc_accuracy <- accuracy(fc, train,
  measures = list(
    point_accuracy_measures,
    interval_accuracy_measures,
    distribution_accuracy_measures
  )
)
```


```{r}
fc_accuracy %>%
  group_by(.model) %>%
  summarise(
    RMSE = mean(RMSE),
    MAE = mean(MAE),
    MASE = mean(MASE),
    Winkler = mean(winkler),
    CRPS = mean(CRPS)
  ) %>%
  arrange(RMSE)
```
