---
title: "data-exploration"
author: "Millie Chapman"
date: "1/29/2021"
output: github_document
---

```{r}
library(tidyverse)
library(ISOweek) 
library(forecast)
library(fable)
library(tsibble)
library(tsibbledata)
library(lubridate)
#> Warning: package 'lubridate' was built under R version 3.6.3
library(dplyr)
```

Null forecast function
```{r}
null_forecast <- function(targets, forecast_year = 2020){
  ## Forecast is just based on historic mean/sd by siteID & week
  model <- targets %>% 
    mutate(iso_week = ISOweek::date2ISOweek(time)) %>%
    separate(iso_week, into = c("year", "week", "day")) %>%
    filter(year < forecast_year) %>%
    group_by(week, siteID) %>%
    summarize(mean_richness = mean(richness, na.rm = TRUE),
              sd_richness = sd(richness, na.rm = TRUE),
              mean_abundance = mean(abundance, na.rm = TRUE),
              sd_abundance = sd(abundance, na.rm = TRUE)
              ) %>% 
    mutate(sd_richness = replace_na(sd_richness, mean(sd_richness, na.rm=TRUE)),
           sd_abundance = replace_na(sd_abundance, mean(sd_abundance, na.rm=TRUE)),
          ) %>% 
    mutate(year = forecast_year)

  ### Express forecasts in terms of replicates instead of analytic mean, sd.
  ### This allows for scoring using CRPS, and generalizes to MCMC-based forecasts
  mcmc_samples <- function(df, n_reps = 500){
    map_dfr(1:nrow(df), 
            function(i) 
              data.frame(siteID = df$siteID[[i]],
                         time = ISOweek::ISOweek2date(paste(df$year[[i]], 
                                                            df$week[[i]], 
                                                            "1", sep = "-")),
                         ensemble = 1:n_reps, 
                         richness = rnorm(n_reps, 
                                          df$mean_richness[[i]], 
                                          df$sd_richness[[i]]),
                         abundance = rnorm(n_reps,
                                           df$mean_abundance[[i]],
                                           df$sd_abundance[[i]])
                         
                        )
            )
  }
  
  n_reps <- 500
  forecast <- mcmc_samples(model, n_reps)
}
```


```{r}
## Get the latest beetle target data.  
download.file("https://data.ecoforecast.org/targets/beetles/beetles-targets.csv.gz",
              "beetles-targets.csv.gz")
targets <-  read_csv("beetles-targets.csv.gz")

## Make the forecast
forecast <- null_forecast(targets)
```


```{r}
forecast <- forecast %>%
  group_by(time, siteID) %>%
  summarise(lower_abundance = quantile(abundance, 0.025, na.rm = TRUE),
            upper_abundance = quantile(abundance, 0.975, na.rm = TRUE),
            lower_richness = quantile(richness, 0.025, na.rm = TRUE),
            upper_richness = quantile(richness, 0.975, na.rm = TRUE),
            abundance = mean(abundance, na.rm = TRUE),
            richness = mean(richness, na.rm = TRUE))
```

```{r}
targets %>% 
    mutate(iso_week = ISOweek::date2ISOweek(time)) %>%
    separate(iso_week, into = c("year", "week", "day")) %>%
    filter(year < 2020) %>%
    group_by(week, siteID) %>%
    summarize(mean_richness = mean(richness, na.rm = TRUE),
              sd_richness = sd(richness, na.rm = TRUE),
              mean_abundance = mean(abundance, na.rm = TRUE),
              sd_abundance = sd(abundance, na.rm = TRUE)
              ) %>% 
    mutate(sd_richness = replace_na(sd_richness, mean(sd_richness, na.rm=TRUE)),
           sd_abundance = replace_na(sd_abundance, mean(sd_abundance, na.rm=TRUE)),
          ) %>% 
    mutate(year = 2020)
```

```{r}
targets_plot <- targets %>% 
    mutate(iso_week = ISOweek::date2ISOweek(time)) %>%
    separate(iso_week, into = c("year", "week", "day")) %>%
    filter(year < 2020)  
```

Abundance plot (for one site)

```{r}
forecast %>%
  filter(siteID == "DSNY") %>%
  ggplot(aes(x = time, y = abundance)) +
  geom_line(color = "blue") +
  geom_ribbon(aes(ymin = lower_abundance, ymax = upper_abundance, col = "blue"), linetype=2, alpha=0.1, color = "blue", fill = "blue") +
  geom_line(aes(x = time, y = abundance), data = targets_plot, color = "black")
```

Richness plot

```{r}
forecast %>%
  filter(siteID == "DSNY") %>%
  ggplot(aes(x = time, y = richness)) +
  geom_line(color = "blue") +
  geom_ribbon(aes(ymin = lower_richness, ymax = upper_richness, col = "blue"), linetype=2, alpha=0.1, color = "blue", fill = "blue") +
  geom_line(aes(x = time, y = richness), data = targets_plot, color = "black")
```


Explore other models

```{r}
targets_ts <- targets %>%
  select(siteID, time, richness) %>%
  mutate(time = as.Date(time)) %>%
  #separate(iso_week, into = c("year", "week", "day")) %>%
  filter(siteID %in% c("DSNY", "OSBS"))

targets_tsb <- as_tsibble(targets_ts, key = siteID, index = time)

autoplot(targets_tsb)


targets_tsb %>% 
  fill_gaps(.full = TRUE) %>%
  model(ets = ETS(box_cox(richness, 0.3)),
        arima = ARIMA(log(richness)),
        snaive = SNAIVE(richness)
  ) %>%
  forecast(h = "2 years") %>% 
  autoplot(level = NULL)
```


