---
title: "Humidity download"
author: "Hudson Northrop"
date: "2/10/21"
output: html_document
---

```{r}
library(tidyverse)
library(neonstore)

```


Get beetle target data
```{r}
## Get the latest beetle target data.  
download.file("https://data.ecoforecast.org/targets/beetles/beetles-targets.csv.gz",
              "beetles-targets.csv.gz")
targets <-  read_csv("beetles-targets.csv.gz")
```

Download weather/humidity data
```{r}
##Get humidity table
humidity <- neon_read(table = "wss_daily_humid-basic", product = "DP4.00001.001")

```

Join humidity table and targets table
```{r}
all_humidities <- humidity %>%
  select(date, siteID, wssRHMean, wssRHMinimum, wssRHMaximum) %>%
  left_join(targets, by = c("date" = "time", "siteID" = "siteID"))
```

Summarize RH data at the 2-week level
This is easiest at the Site Level
```{r}
##Select a site, for example 'BONA'
bona <- all_humidities %>%
  filter(siteID  == "BONA")
##Filter for dates at which there is at least one richness or abundance observation
dates <- bona %>%
  mutate("abundance.na" = if_else(is.na(abundance), 1, 0), "richness.na" = if_else(is.na(richness), 1, 0)) %>%
  mutate("sum.na" = abundance.na + richness.na) %>%
  filter(sum.na %in% c(0,1)) %>%
  distinct(date)

#Set up vectors to store 2 week info in
meanRH <- NULL
minRH <- NULL
maxRH <- NULL

#For loop that calculates the 2 week info, based on the last 2 weeks from each beetle measurement
for(i in 1:length(dates$date)) {
  a <- filter(bona, date %in% c(dates$date[i]-0:13 ))
  meanRH[i] <- mean(a$wssRHMean, na.rm = TRUE)
  minRH[i] <- min(a$wssRHMinimum, na.rm = TRUE)
  maxRH[i] <- max(a$wssRHMaximum, na.rm = TRUE)
}

bona_final <- bona %>%
  mutate("abundance.na" = if_else(is.na(abundance), 1, 0), "richness.na" = if_else(is.na(richness), 1, 0)) %>%
  mutate("sum.na" = abundance.na + richness.na) %>%
  filter(sum.na %in% c(0,1)) %>%
  select(siteID, date, richness, abundance) %>%
  bind_cols("meanRH" = meanRH,"minRH" =  minRH,"maxRH"= maxRH)

```

Some basic EDA
```{r}
##Scatterplots of RH metrics and richness/abundance

bona_final %>%
  ggplot(aes(x = meanRH, y = richness)) +
  geom_point() +
  geom_smooth()

bona_final %>%
  ggplot(aes(x = minRH, y = richness)) +
  geom_point() +
  geom_smooth()

bona_final %>%
  ggplot(aes(x = maxRH, y = richness)) +
  geom_point() +
  geom_smooth()

bona_final %>%
  ggplot(aes(x = meanRH, y = abundance)) +
  geom_point() +
  geom_smooth()

bona_final %>%
  ggplot(aes(x = minRH, y = abundance)) +
  geom_point() +
  geom_smooth()

bona_final %>%
  ggplot(aes(x = maxRH, y = abundance)) +
  geom_point() +
  geom_smooth()

```

Looking at distributions
```{r}
bona_final %>%
  ggplot(aes(x = richness)) +
  geom_density()

bona_final %>%
  ggplot(aes(x = abundance)) +
  geom_density()

bona_final %>%
  ggplot(aes(x = meanRH)) +
  geom_density()

bona_final %>%
  ggplot(aes(x = minRH)) +
  geom_density()

bona_final %>%
  ggplot(aes(x = maxRH)) +
  geom_density()

```